POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Anthonyyyy",
  "username": "Tonyyy",
  "email": "atspennn.dev@gmail.com"
}



###
GET http://localhost:3000/api/users HTTP/1.1